[package]
name = "capy-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
capy.workspace = true


[features]
portable = ["capy/portable"]
default = ["portable"]

[[bin]]
name = "capyvm"
path = "src/main.rs"
