[target.x86_64-apple-darwin]
rustflags = ["-Clink-args=-Wl,-rpath,@loader_path/"]
[target.aarch64-apple-darwin]
rustflags = ["-Clink-args=-Wl,-rpath,@loader_path/"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-args=-Wl,-rpath,$ORIGIN/",
    "-Clink-arg=-Wl,--no-rosegment",
    "-Cprefer-dynamic",
]
[target.i686-unknown-linux-gnu]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.aarch64-unknown-linux-musl]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.x86_64-unknown-linux-musl]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.i686-unknown-linux-musl]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
[target.armv7-unknown-linux-musleabihf]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN/"]
